# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  routing_loader:
    include_format: false
    default_format: json
  body_listener: true
  format_listener:
    rules:
      - { path: '^/api', priorities: [ 'json' ], fallback_format: 'json'}
      - { path: '^/', priorities: [ 'text/html', '*/*'], fallback_format: html, prefer_extension: true }
  exception:
    enabled: true
  # param_fetcher_listener: true
  view:
    view_response_listener:  'force'
    formats:
      json: true
