#index:
#    path: /
#    controller: App\Controller\DefaultController::index

criteria_list:
  type: rest
  resource: App\Controller\CriteriaListController
  prefix: api
competence_list:
  type: rest
  resource: App\Controller\CriteriaListController
  prefix: api
career_form:
  type: rest
  resource: App\Controller\CareerFormController
  prefix: api
career_profile:
  type: rest
  resource: App\Controller\CareerProfileController
  prefix: api
profession:
  type: rest
  resource: App\Controller\ProfessionController
  prefix: api
user:
  type: rest
  resource: App\Controller\UserController
  prefix: api
manager_feedback:
  type: rest
  resource: App\Controller\ManagerFeedbackController
  prefix: api
user_answer:
  type: rest
  resource: App\Controller\UserAnswerController
  prefix: api
#api_login_check:
#  path: /api/login_check
